#pragma once

const struct decoded_key key_neo2_mapping[] = {
    {KC_SPC, 1, 0},  // " "
    {KC_Y, 3, 0},    // !
    {KC_COMM, 3, 0}, // "
    {KC_Z, 3, 0},    // #
    {KC_X, 3, 0},    // $
    {KC_M, 3, 0},    // %
    {KC_P, 3, 0},    // &
    {KC_DOT, 3, 0},  // '
    {KC_J, 3, 0},    // (
    {KC_K, 3, 0},    // )
    {KC_G, 3, 0},    // *
    {KC_N, 3, 0},    // +
    {KC_COMM, 1, 0}, // ,
    {KC_L, 3, 0},    // -
    {KC_DOT, 1, 0},  // .
    {KC_S, 3, 0},    // /
    {KC_0, 1, 0},    // 0
    {KC_1, 1, 0},    // 1
    {KC_2, 1, 0},    // 2
    {KC_3, 1, 0},    // 3
    {KC_4, 1, 0},    // 4
    {KC_5, 1, 0},    // 5
    {KC_6, 1, 0},    // 6
    {KC_7, 1, 0},    // 7
    {KC_8, 1, 0},    // 8
    {KC_9, 1, 0},    // 9
    {KC_SCLN, 3, 0}, // :
    {KC_SLSH, 3, 0}, // ;
    {KC_U, 3, 0},    // <
    {KC_O, 3, 0},    // =
    {KC_I, 3, 0},    // >
    {KC_H, 3, 0},    // ?
    {KC_QUOT, 3, 0}, // @
    {KC_D, 2, 0},    // A
    {KC_N, 2, 0},    // B
    {KC_R, 2, 0},    // C
    {KC_SCLN, 2, 0}, // D
    {KC_F, 2, 0},    // E
    {KC_O, 2, 0},    // F
    {KC_I, 2, 0},    // G
    {KC_U, 2, 0},    // H
    {KC_S, 2, 0},    // I
    {KC_SLSH, 2, 0}, // J
    {KC_Y, 2, 0},    // K
    {KC_E, 2, 0},    // L
    {KC_M, 2, 0},    // M
    {KC_J, 2, 0},    // N
    {KC_G, 2, 0},    // O
    {KC_V, 2, 0},    // P
    {KC_P, 2, 0},    // Q
    {KC_K, 2, 0},    // R
    {KC_H, 2, 0},    // S
    {KC_L, 2, 0},    // T
    {KC_A, 2, 0},    // U
    {KC_W, 2, 0},    // V
    {KC_T, 2, 0},    // W
    {KC_Q, 2, 0},    // X
    {KC_QUOT, 2, 0}, // Y
    {KC_B, 2, 0},    // Z
    {KC_E, 3, 0},    // [
    {KC_A, 3, 0},    // '\'
    {KC_R, 3, 0},    // ]
    {KC_T, 3, 0},    // ^
    {KC_W, 3, 0},    // _
    {KC_B, 3, 0},    // `
    {KC_D, 1, 0},    // a
    {KC_N, 1, 0},    // b
    {KC_R, 1, 0},    // c
    {KC_SCLN, 1, 0}, // d
    {KC_F, 1, 0},    // e
    {KC_O, 1, 0},    // f
    {KC_I, 1, 0},    // g
    {KC_U, 1, 0},    // h
    {KC_S, 1, 0},    // i
    {KC_SLSH, 1, 0}, // j
    {KC_Y, 1, 0},    // k
    {KC_E, 1, 0},    // l
    {KC_M, 1, 0},    // m
    {KC_J, 1, 0},    // n
    {KC_G, 1, 0},    // o
    {KC_V, 1, 0},    // p
    {KC_P, 1, 0},    // q
    {KC_K, 1, 0},    // r
    {KC_H, 1, 0},    // s
    {KC_L, 1, 0},    // t
    {KC_A, 1, 0},    // u
    {KC_W, 1, 0},    // v
    {KC_T, 1, 0},    // w
    {KC_Q, 1, 0},    // x
    {KC_QUOT, 1, 0}, // y
    {KC_B, 1, 0},    // z
    {KC_D, 3, 0},    // {
    {KC_C, 3, 0},    // |
    {KC_F, 3, 0},    // }
    {KC_V, 3, 0},    // ~
    {KC_SPC, 5, 0},  //   (U+00A0)
    {KC_Y, 4, 0},    // ¡
    {KC_6, 3, 0},    // ¢
    {KC_6, 4, 0},    // £
    {KC_7, 4, 0},    // ¤
    {KC_7, 3, 0},    // ¥
    {KC_2, 2, 0},    // §
    {KC_1, 4, 0},    // ª
    {KC_5, 2, 0},    // «
    {KC_1, 6, 0},    // ¬
    {KC_MINS, 6, 0}, // ­ (U+00AD)
    {KC_1, 2, 0},    // °
    {KC_PPLS, 3, 0}, // ±
    {KC_2, 3, 0},    // ²
    {KC_3, 3, 0},    // ³
    {KC_5, 4, 0},    // ·
    {KC_1, 3, 0},    // ¹
    {KC_2, 4, 0},    // º
    {KC_4, 2, 0},    // »
    {KC_H, 4, 0},    // ¿
    {KC_C, 2, 0},    // Ä
    {KC_X, 2, 0},    // Ö
    {KC_Y, 6, 0},    // ×
    {KC_Z, 2, 0},    // Ü
    {KC_LBRC, 1, 0}, // ß
    {KC_C, 1, 0},    // ä
    {KC_X, 1, 0},    // ö
    {KC_PSLS, 3, 0}, // ÷
    {KC_Z, 1, 0},    // ü
    {KC_LBRC, 3, 0}, // ſ
    {KC_I, 6, 0},    // Γ
    {KC_SCLN, 6, 0}, // Δ
    {KC_SLSH, 6, 0}, // Θ
    {KC_E, 6, 0},    // Λ
    {KC_Q, 6, 0},    // Ξ
    {KC_V, 6, 0},    // Π
    {KC_H, 6, 0},    // Σ
    {KC_O, 6, 0},    // Φ
    {KC_U, 6, 0},    // Ψ
    {KC_T, 6, 0},    // Ω
    {KC_D, 5, 0},    // α
    {KC_N, 5, 0},    // β
    {KC_I, 5, 0},    // γ
    {KC_N, 5, 0},    // δ
    {KC_F, 5, 0},    // ε
    {KC_B, 5, 0},    // ζ
    {KC_C, 5, 0},    // η
    {KC_SLSH, 5, 0}, // θ
    {KC_S, 5, 0},    // ι
    {KC_Y, 5, 0},    // κ
    {KC_E, 5, 0},    // λ
    {KC_M, 5, 0},    // μ
    {KC_J, 5, 0},    // ν
    {KC_Q, 5, 0},    // ξ
    {KC_G, 5, 0},    // ο
    {KC_V, 5, 0},    // π
    {KC_K, 5, 0},    // ρ
    {KC_LBRC, 5, 0}, // ς
    {KC_H, 5, 0},    // σ
    {KC_L, 5, 0},    // τ
    {KC_QUOT, 5, 0}, // υ
    {KC_O, 5, 0},    // φ
    {KC_R, 5, 0},    // χ
    {KC_U, 5, 0},    // ψ
    {KC_T, 5, 0},    // ω
    {KC_DOT, 5, 0},  // ϑ
    {KC_P, 5, 0},    // ϕ
    {KC_7, 5, 0},    // ϰ
    {KC_COMM, 5, 0}, // ϱ
    {KC_X, 5, 0},    // ϵ
    {KC_LBRC, 2, 0}, // ẞ
    {KC_MINS, 5, 0}, // ‑ (U+2011)
    {KC_COMM, 2, 0}, // –
    {KC_MINS, 2, 0}, // —
    {KC_9, 3, 0},    // ‘
    {KC_0, 3, 0},    // ’
    {KC_8, 3, 0},    // ‚
    {KC_9, 2, 0},    // “
    {KC_0, 2, 0},    // ”
    {KC_8, 2, 0},    // „
    {KC_P9, 2, 0},   // †
    {KC_DOT, 2, 0},  // •
    {KC_P6, 2, 0},   // ‣
    {KC_Q, 3, 0},    // …
    {KC_SPC, 6, 0},  //   (U+202F)
    {KC_P0, 5, 0},   // ‰
    {KC_PDOT, 5, 0}, // ′
    {KC_PDOT, 6, 0}, // ″
    {KC_5, 3, 0},    // ‹
    {KC_4, 3, 0},    // ›
    {KC_PSLS, 4, 0}, // ⁄
    {KC_0, 5, 0},    // ₀
    {KC_1, 5, 0},    // ₁
    {KC_2, 5, 0},    // ₂
    {KC_3, 5, 0},    // ₃
    {KC_7, 2, 0},    // €
    {KC_R, 6, 0},    // ℂ
    {KC_3, 2, 0},    // ℓ
    {KC_J, 6, 0},    // ℕ
    {KC_3, 4, 0},    // №
    {KC_P, 6, 0},    // ℚ
    {KC_K, 6, 0},    // ℝ
    {KC_B, 6, 0},    // ℤ
    {KC_C, 6, 0},    // ℵ
    {KC_P4, 3, 0},   // ←
    {KC_P8, 3, 0},   // ↑
    {KC_P6, 3, 0},   // →
    {KC_P2, 3, 0},   // ↓
    {KC_P1, 3, 0},   // ↔
    {KC_P7, 3, 0},   // ↕
    {KC_DOT, 6, 0},  // ↦
    {KC_P3, 3, 0},   // ⇌
    {KC_N, 6, 0},    // ⇐
    {KC_COMM, 6, 0}, // ⇒
    {KC_M, 6, 0},    // ⇔
    {KC_D, 6, 0},    // ∀
    {KC_L, 6, 0},    // ∂
    {KC_F, 6, 0},    // ∃
    {KC_0, 6, 0},    // ∅
    {KC_QUOT, 6, 0}, // ∇
    {KC_G, 6, 0},    // ∈
    {KC_LBRC, 4, 0}, // −
    {KC_PPLS, 4, 0}, // ∓
    {KC_PPLS, 6, 0}, // ∔
    {KC_PMNS, 4, 0}, // ∖
    {KC_LBRC, 6, 0}, // ∘
    {KC_W, 6, 0},    // √
    {KC_9, 6, 0},    // ∝
    {KC_8, 6, 0},    // ∞
    {KC_5, 6, 0},    // ∡
    {KC_PSLS, 6, 0}, // ∣
    {KC_6, 6, 0},    // ∥
    {KC_3, 6, 0},    // ∧
    {KC_2, 6, 0},    // ∨
    {KC_X, 6, 0},    // ∩
    {KC_Z, 6, 0},    // ∪
    {KC_S, 6, 0},    // ∫
    {KC_PMNS, 6, 0}, // ∸
    {KC_NLCK, 5, 0}, // ≈
    {KC_NLCK, 4, 0}, // ≠
    {KC_NLCK, 6, 0}, // ≡
    {KC_P1, 5, 0},   // ≤
    {KC_P3, 5, 0},   // ≥
    {KC_P7, 5, 0},   // ≪
    {KC_P9, 5, 0},   // ≫
    {KC_A, 6, 0},    // ⊂
    {KC_P6, 5, 0},   // ⊃
    {KC_P4, 6, 0},   // ⊆
    {KC_P6, 6, 0},   // ⊇
    {KC_PPLS, 5, 0}, // ⊕
    {KC_PMNS, 5, 0}, // ⊖
    {KC_PAST, 6, 0}, // ⊛
    {KC_PAST, 5, 0}, // ⊙
    {KC_4, 6, 0},    // ⊥
    {KC_P5, 5, 0},   // ⊶
    {KC_P5, 6, 0},   // ⊷
    {KC_P8, 6, 0},   // ⋂
    {KC_P2, 6, 0},   // ⋃
    {KC_PAST, 3, 0}, // ⋅
    {KC_PSLS, 5, 0}, // ⌀
    {KC_P7, 6, 0},   // ⌈
    {KC_P9, 6, 0},   // ⌉
    {KC_P1, 6, 0},   // ⌊
    {KC_P3, 6, 0},   // ⌋
    {KC_P0, 2, 0},   // ␣
    {KC_P0, 6, 0},   // □
    {KC_P3, 2, 0},   // ♠
    {KC_P4, 2, 0},   // ♣
    {KC_P2, 2, 0},   // ♥
    {KC_P1, 2, 0},   // ♦
    {KC_4, 5, 0},    // ♀
    {KC_5, 5, 0},    // ♂
    {KC_6, 5, 0},    // ⚥
    {KC_P7, 2, 0},   // ✔
    {KC_P8, 2, 0},   // ✘
    {KC_8, 5, 0},    // ⟨
    {KC_9, 5, 0},    // ⟩

    {KC_GRV, 1, DECODED_KEY_ONESHOT},  // ^
    {KC_GRV, 2, DECODED_KEY_ONESHOT},  //  ̌
    {KC_GRV, 3, DECODED_KEY_ONESHOT},  // ↻
    {KC_GRV, 4, DECODED_KEY_ONESHOT},  //  ̇
    {KC_GRV, 5, DECODED_KEY_ONESHOT},  // ˞
    {KC_GRV, 6, DECODED_KEY_ONESHOT},  // .
    {KC_EQL, 1, DECODED_KEY_ONESHOT},  // `
    {KC_EQL, 2, DECODED_KEY_ONESHOT},  // ¸
    {KC_EQL, 3, DECODED_KEY_ONESHOT},  // °
    {KC_EQL, 4, DECODED_KEY_ONESHOT},  //  ̈
    {KC_EQL, 5, DECODED_KEY_ONESHOT},  // ῾
    {KC_EQL, 5, DECODED_KEY_ONESHOT},  //  ̄
    {KC_RBRC, 1, DECODED_KEY_ONESHOT}, // ´
    {KC_RBRC, 2, DECODED_KEY_ONESHOT}, // ˜
    {KC_RBRC, 3, DECODED_KEY_ONESHOT}, // /
    {KC_RBRC, 4, DECODED_KEY_ONESHOT}, // ˝
    {KC_RBRC, 5, DECODED_KEY_ONESHOT}, // ᾿
    {KC_RBRC, 6, DECODED_KEY_ONESHOT}, // ˘
    {KC_P9, 2, DECODED_KEY_ONESHOT},   // →

    {KC_NLCK, 2, DECODED_KEY_ONESHOT}, //  leftwards tab
};
